<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>DieCutCatalog.Mobile</RootNamespace>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>DieCut Catalog</ApplicationTitle>
    <ApplicationId>com.flexprint.diecutcatalog</ApplicationId>
    <ApplicationDisplayVersion>0.2.0</ApplicationDisplayVersion>
    <ApplicationVersion>2</ApplicationVersion>
    <SupportedOSPlatformVersion>29.0</SupportedOSPlatformVersion>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
  </PropertyGroup>
  <ItemGroup>
    <MauiIcon Include="Resources/AppIcon/appicon.png" />
    <MauiSplashScreen Include="Resources/Splash/splash_logo.png" Color="#FFFFFF" BaseSize="128,128" />
    <MauiImage Include="Resources/Images/*" />
    <MauiFont Include="Resources/Fonts/*" />
    <MauiAsset Include="Resources/Raw/**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.9" />
  </ItemGroup>
</Project>
