<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../DieCutCatalog.Application/DieCutCatalog.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets/flexprint-logo.png" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets/flexprint-logo.ico</ApplicationIcon>
  </PropertyGroup>

</Project>